name: adaptable_widget
description: A collection of widgets that adapt to match the preferred style of the current platform
version: 0.1.3
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/adaptable_widget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
